api_keys:
  google: ""
  telethon: ""

telegram_channels:
  - "abualiexpress"
  - "fajernews"
  - "jeninqassam"
  - "muthanapress84"
  - "PalpostN"
  - "ramreports"
  - "amitsegal"
  - "hamza20300"
  - "LebUpdate"
  - "nablusnews2"
  - "qassambrigades"
  - "sarayaps"
  - "dcdgaza"
  - "hpress"
  - "manniefabian"
  - "newsil2022"
  - "QudsN"
  - "southfirstresponders"
  - "Eyeonpalestine2"
  - "idfofficial"
  - "mohnadQ"
  - "Nuseirat1"
  - "QudsNen"
  - "the_slaughter710"