secret_keys:
  google:
    api_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  telethon:
    api_id: 123465789
    api_hash: "00000000000000000000000000000000"
    phone: "+1 (000) 000-0000"

telegram_channels:
  - "abualiexpress"
  - "fajernews"
  - "jeninqassam"
  - "muthanapress84"
  - "PalpostN"
  - "ramreports"
  - "amitsegal"
  - "hamza20300"
  - "LebUpdate"
  - "nablusnews2"
  - "qassambrigades"
  - "sarayaps"
  - "dcdgaza"
  - "hpress"
  - "manniefabian"
  - "newsil2022"
  - "QudsN"
  - "southfirstresponders"
  - "Eyeonpalestine2"
  - "idfofficial"
  - "mohnadQ"
  - "Nuseirat1"
  - "QudsNen"
  - "the_slaughter710"